version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_eddi-public-wechat
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=eddi-public-wechat
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Rc19931020
      - MYSQL_ADDRESS=sh-cynosdbmysql-grp-3jmr69ni.sql.tencentcdb.com:25637
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
networks:
  default:
    name: wxcb0
    external: true
